### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by lens0021** [femiwiki/FemiwikiSkin#202]
```
[e11a2b052114aab91acd214e] /load.php?lang=ko&modules=ext.echo.styles.badge%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cmediawiki.ui.icon%7Coojs-ui.styles.icons-alerts%7Cskins.vector.icons%2Cstyles%7Cwikibase.client.data-bridge.externalModifiers%7Cwikibase.client.init&only=styles&skin=vector
TypeError from line 116 of /srv/femiwiki.com/includes/resourceloader/ResourceLoaderOOUIImageModule.php:
Return value of ResourceLoaderOOUIImageModule::loadOOUIDefinition() must be of the type array, bool returned

Backtrace:

#0 /srv/femiwiki.com/includes/resourceloader/ResourceLoaderOOUIImageModule.php(43): ResourceLoaderOOUIImageModule->loadOOUIDefinition(string, string)
#1 /srv/femiwiki.com/includes/resourceloader/ResourceLoaderImageModule.php(420): ResourceLoaderOOUIImageModule->loadFromDefinition()
#2 /srv/femiwiki.com/includes/resourceloader/ResourceLoaderModule.php(842): ResourceLoaderImageModule->getDefinitionSummary(ResourceLoaderContext)
#3 /srv/femiwiki.com/includes/resourceloader/ResourceLoader.php(775): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#4 [internal function]: ResourceLoader->{closure}(string)
#5 /srv/femiwiki.com/includes/resourceloader/ResourceLoader.php(787): array_map(Closure, array)
#6 /srv/femiwiki.com/includes/resourceloader/ResourceLoader.php(874): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#7 /srv/femiwiki.com/load.php(51): ResourceLoader->respond(ResourceLoaderContext)
#8 /srv/femiwiki.com/load.php(38): wfLoadMain()
#9 {main}
```

`wfLoadSkin( 'Femiwiki' );` 시 다른 스킨까지 모두 문제가 생겨 위와 같은 에러가 발생합니다.

**Comment by lens0021** [comment]
skin.json `"OOUIThemePaths"`에 `{"localBasePath": "resources/ooui", "remoteSkinPath": "Femiwiki/resources/ooui"}`을 적었을 때 에러가 나는 `$dataPath`:
```
modules/ve-mw/ui/styles/femiwiki/ve.ui.Icons.json
```

skin.json에서 path 관련 부분 지웠을 때 에러 나는 `$dataPath`:
```
ResourceLoaderFilePath Object
(
    [localBasePath:protected] =>; /srv/femiwiki.com/skins/Femiwiki/resources
    [remoteBasePath:protected] => /skins/Femiwiki
    [path:protected] => icons-alerts.json
)
```

**Comment by lens0021** [comment]
업스트림에 글을 올렸습니다 https://phabricator.wikimedia.org/T260059

**Comment by lens0021** [comment]
업스트림 버그 패치됐습니다.
