### ISSUE TITLE
GlobalTitleFail

### ISSUE THREAD

**Issue by lens0021** [femiwiki/FemiwikiSkin#264]
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /srv/femiwiki.com/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /srv/femiwiki.com/includes/language/Message.php(922): Message->parseText(string)
#2 /srv/femiwiki.com/includes/language/Message.php(953): Message->format(string)
#3 [internal function]: Message->__toString()
#4 /srv/femiwiki.com/includes/skins/Skin.php(2356): htmlspecialchars(Message)
#5 /srv/femiwiki.com/includes/skins/Skin.php(2498): Skin->makeLink(string, array, array)
#6 /srv/femiwiki.com/skins/Femiwiki/includes/SkinFemiwiki.php(197): Skin->makeListItem(string, array, array)
#7 /srv/femiwiki.com/includes/skins/SkinMustache.php(243): MediaWiki\Skins\Femiwiki\SkinFemiwiki->getPortletData(string, array)
#8 /srv/femiwiki.com/includes/skins/SkinMustache.php(198): SkinMustache->getPortletsTemplateData()
#9 /srv/femiwiki.com/skins/Femiwiki/includes/SkinFemiwiki.php(44): SkinMustache->getTemplateData()
#10 /srv/femiwiki.com/includes/skins/SkinMustache.php(136): MediaWiki\Skins\Femiwiki\SkinFemiwiki->getTemplateData()
#11 /srv/femiwiki.com/includes/skins/SkinTemplate.php(146): SkinMustache->generateHTML()
#12 /srv/femiwiki.com/includes/OutputPage.php(2634): SkinTemplate->outputPage()
#13 /srv/femiwiki.com/includes/MediaWiki.php(927): OutputPage->output(boolean)
#14 /srv/femiwiki.com/includes/MediaWiki.php(940): MediaWiki::{closure}()
#15 /srv/femiwiki.com/includes/MediaWiki.php(546): MediaWiki->main()
#16 /srv/femiwiki.com/index.php(53): MediaWiki->run()
#17 /srv/femiwiki.com/index.php(46): wfIndexMain()
#18 {main}
```

**Comment by lens0021** [comment]
occurs in Vector too.
