### ISSUE TITLE
PHP Notice: Undefined index: images

### ISSUE THREAD

**Issue by paladox** [femiwiki/FemiwikiSkin#311]
Traceback:

```
from /srv/mediawiki/w/includes/resourceloader/ResourceLoaderOOUIIconPackModule.php(66)
#0 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderOOUIIconPackModule.php(66): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderOOUIImageModule.php(43): ResourceLoaderOOUIIconPackModule->loadOOUIDefinition(string, string)
#2 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderImageModule.php(421): ResourceLoaderOOUIImageModule->loadFromDefinition()
#3 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderModule.php(859): ResourceLoaderImageModule->getDefinitionSummary(ResourceLoaderContext)
#4 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(207): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#5 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderStartUpModule.php(407): ResourceLoaderStartUpModule->getModuleRegistrations(ResourceLoaderContext)
#6 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderModule.php(753): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#7 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderModule.php(721): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#8 /srv/mediawiki/w/includes/resourceloader/ResourceLoaderModule.php(856): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#9 /srv/mediawiki/w/includes/resourceloader/ResourceLoader.php(772): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#10 [internal function]: ResourceLoader->{closure}(string)
#11 /srv/mediawiki/w/includes/resourceloader/ResourceLoader.php(784): array_map(Closure, array)
#12 /srv/mediawiki/w/includes/resourceloader/ResourceLoader.php(871): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#13 /srv/mediawiki/w/load.php(51): ResourceLoader->respond(ResourceLoaderContext)
#14 /srv/mediawiki/w/load.php(38): wfLoadMain()
#15 {main}
```

I debuged to find that it was this skin causing all the logspam to do with the icons.

Running MediaWiki 1.36 and php 7.3

**Comment by lens0021** [comment]
I have reproduced the problem and found the cause. Executing `npm install` or `yarn` in the skin directory is necessary as this skin requires some npm dependencies. Or simply you can download the [tar.gz files](https://github.com/femiwiki/FemiwikiSkin/releases) ship with the node modules.

Could you test again with the node modules? @paladox

**Comment by lens0021** [comment]
If what I think is right, 4f5842424f623c46958ffecbf7fc44678156bf13 causes this.
