### ISSUE TITLE
Original exception: [7959ea97f443926a7dea6b47] /wiki/Main_Page ParseError: syntax error, unexpected '='

### ISSUE THREAD

**Issue by jdlrobson** [femiwiki/FemiwikiSkin#531]
Might be a PHP version error but I was getting this error on https://skins-demo.wmflabs.org/wiki/Main_Page so had to disable the live preview mode. Apologies in advance if this is an issue my end, I haven't had a chance to investigate yet.

```
MediaWiki internal error.

Original exception: [7959ea97f443926a7dea6b47] /wiki/Main_Page ParseError: syntax error, unexpected '='
Backtrace:
from /vagrant/mediawiki/skins/Femiwiki/includes/HookHandler/Portlet.php(283)
#0 [internal function]: AutoLoader::autoload(string)
#1 /vagrant/mediawiki/vendor/wikimedia/object-factory/src/ObjectFactory.php(247): spl_autoload_call(string)
#2 /vagrant/mediawiki/vendor/wikimedia/object-factory/src/ObjectFactory.php(152): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec(array, array)
#3 /vagrant/mediawiki/includes/HookContainer/HookContainer.php(473): Wikimedia\ObjectFactory\ObjectFactory->createObject(array)
#4 /vagrant/mediawiki/includes/HookContainer/HookContainer.php(156): MediaWiki\HookContainer\HookContainer->getHandlers(string, array)
#5 /vagrant/mediawiki/includes/HookContainer/HookRunner.php(3022): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#6 /vagrant/mediawiki/includes/skins/SkinTemplate.php(573): MediaWiki\HookContainer\HookRunner->onPersonalUrls(array, Title, SkinMustache)
#7 /vagrant/mediawiki/includes/skins/SkinTemplate.php(1229): SkinTemplate->buildPersonalUrls(boolean)
#8 /vagrant/mediawiki/includes/skins/SkinTemplate.php(781): SkinTemplate->buildContentNavigationUrlsInternal()
#9 /vagrant/mediawiki/includes/skins/SkinTemplate.php(219): SkinTemplate->getPortletsTemplateData()
#10 /vagrant/mediawiki/includes/skins/SkinMustache.php(81): SkinTemplate->getTemplateData()
#11 /vagrant/mediawiki/includes/skins/SkinMustache.php(58): SkinMustache->getTemplateData()
#12 /vagrant/mediawiki/includes/skins/SkinTemplate.php(167): SkinMustache->generateHTML()
#13 /vagrant/mediawiki/includes/OutputPage.php(2809): SkinTemplate->outputPage()
#14 /vagrant/mediawiki/includes/MediaWiki.php(926): OutputPage->output(boolean)
#15 /vagrant/mediawiki/includes/MediaWiki.php(939): MediaWiki::{closure}()
#16 /vagrant/mediawiki/includes/MediaWiki.php(566): MediaWiki->main()
#17 /vagrant/mediawiki/index.php(50): MediaWiki->run()
#18 /vagrant/mediawiki/index.php(46): wfIndexMain()
#19 /var/www/w/index.php(5): require(string)
#20 {main}

Exception caught inside exception handler: [7959ea97f443926a7dea6b47] /wiki/Main_Page ParseError: syntax error, unexpected '='
Backtrace:
from /vagrant/mediawiki/skins/Femiwiki/includes/HookHandler/Portlet.php(283)
#0 [internal function]: AutoLoader::autoload(string)
#1 /vagrant/mediawiki/vendor/wikimedia/object-factory/src/ObjectFactory.php(247): spl_autoload_call(string)
#2 /vagrant/mediawiki/vendor/wikimedia/object-factory/src/ObjectFactory.php(152): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec(array, array)
#3 /vagrant/mediawiki/includes/HookContainer/HookContainer.php(473): Wikimedia\ObjectFactory\ObjectFactory->createObject(array)
#4 /vagrant/mediawiki/includes/HookContainer/HookContainer.php(156): MediaWiki\HookContainer\HookContainer->getHandlers(string, array)
#5 /vagrant/mediawiki/includes/HookContainer/HookRunner.php(3022): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#6 /vagrant/mediawiki/includes/skins/SkinTemplate.php(573): MediaWiki\HookContainer\HookRunner->onPersonalUrls(array, Title, SkinMustache)
#7 /vagrant/mediawiki/includes/skins/SkinTemplate.php(1229): SkinTemplate->buildPersonalUrls(boolean)
#8 /vagrant/mediawiki/includes/skins/SkinTemplate.php(781): SkinTemplate->buildContentNavigationUrlsInternal()
#9 /vagrant/mediawiki/includes/skins/SkinTemplate.php(219): SkinTemplate->getPortletsTemplateData()
#10 /vagrant/mediawiki/includes/skins/SkinMustache.php(81): SkinTemplate->getTemplateData()
#11 /vagrant/mediawiki/includes/skins/SkinMustache.php(58): SkinMustache->getTemplateData()
#12 /vagrant/mediawiki/includes/skins/SkinTemplate.php(167): SkinMustache->generateHTML()
#13 /vagrant/mediawiki/includes/OutputPage.php(2809): SkinTemplate->outputPage()
#14 /vagrant/mediawiki/includes/exception/MWExceptionRenderer.php(157): OutputPage->output()
#15 /vagrant/mediawiki/includes/exception/MWExceptionRenderer.php(76): MWExceptionRenderer::reportHTML(ParseError)
#16 /vagrant/mediawiki/includes/exception/MWExceptionHandler.php(107): MWExceptionRenderer::output(ParseError, integer)
#17 /vagrant/mediawiki/includes/exception/MWExceptionHandler.php(204): MWExceptionHandler::report(ParseError)
#18 /vagrant/mediawiki/includes/MediaWiki.php(588): MWExceptionHandler::handleException(ParseError, string)
#19 /vagrant/mediawiki/index.php(50): MediaWiki->run()
#20 /vagrant/mediawiki/index.php(46): wfIndexMain()
#21 /var/www/w/index.php(5): require(string)
#22 {main}

```

**Comment by jdlrobson** [comment]
what version of PHP does Femiwiki need? It seems Wikimedia Cloud VPS still  only supports  7.2.31 :(

**Comment by lens0021** [comment]
This repository does not yet have parallel CIs per PHP versions but is needed to prepare for the upcoming 8.0. I will consider 7.2 when building it.
